back_end_notes/django/advanced_django_notes/cbv_project/cbv_app/urls.py
from django.urls import path
from . import views

app_name = "cbv_app"

urlpatterns = [
    path("", views.SchoolListView.as_view(), name="list"),
    path("create", views.SchoolCreateView.as_view(), name="create"),
    path("update/<slug:pk>", views.SchoolUpdateView.as_view(), name="update"),
    path("delete/<slug:pk>", views.SchoolDeleteView.as_view(), name="delete"),
    path("<slug:pk>", views.SchoolDetailView.as_view(), name="detail"),
]

back_end_notes/django/advanced_django_notes/cbv_project/cbv_project/urls.py
from django.contrib import admin
from django.urls import path, include
from cbv_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.IndexView.as_view()),
    path("cbv_app/", include("cbv_app.urls"), name="cbv_app")
]

back_end_notes/django/advanced_django_notes/cbv_project/cbv_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("cbv_app:detail", kwargs={"pk": self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name="students", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

back_end_notes/django/advanced_django_notes/cbv_project/cbv_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponse
from . import models

# Create your views here.
class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        # **kwargs -> keyword arguments
            # gives corresponding arguments as dictionaries

        # *args -> arguments
            # passes all arguments as a tuple

        context = super().get_context_data(**kwargs)
        context["inject_me"] = "BASIC INJECTION EXAMPLE!"
        return context

class SchoolListView(ListView):
    model = models.School
     # returns school_list -> list of school objects

    context_object_name = "schools"
    template_name = "cbv_app/school_list.html"


class SchoolDetailView(DetailView):
    model = models.School
    context_object_name = "school_detail"
    template_name = "cbv_app/school_detail.html"

class SchoolCreateView(CreateView):
    model = models.School
    template_name = "cbv_app/school_form.html"
    fields = ("name", "principal", "location")

class SchoolUpdateView(UpdateView):
    model = models.School
    fields = ("name", "principal")

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url =  reverse_lazy("cbv_app:list")

back_end_notes/django/advanced_django_notes/cbv_project/cbv_app/templates/cbv_app/cbv_app_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Base</title>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'cbv_app:list' %}">Schools</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href=""></a></li>
            </ul>
        </nav>
        <div class="container">
                {% block body_block %}
                {% endblock %}
        </div>
    </body>
</html>

back_end_notes/django/advanced_django_notes/cbv_project/cbv_app/templates/cbv_app/school_confirm_delete.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block%}
    <h1> Delete {{school.name}}?</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'cbv_app:detail' pk=school.pk %}">Cancel</a>
    </form>

{% endblock %}

back_end_notes/django/advanced_django_notes/cbv_project/cbv_app/templates/cbv_app/school_detail.html
{% extends "cbv_app/cbv_app_base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the School Detail Page!</h1>
        <h2>School Details:</h2>
        <p>{{school_detail.name}}</p>
        <p>Principal: {{school_detail.principal}}</p>
        <p>Location: {{school_detail.location}} </p>
        <h3>Students:</h3>
            {% for student in school_detail.students.all %}
                <p>{{student.name}} who is {{student.age}} years old.</p>
            {% endfor %}
    </div>

    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'cbv_app:update' pk=school_detail.pk %}">Update</a></p>
    </div>
{% endblock %}

back_end_notes/django/advanced_django_notes/cbv_project/cbv_app/templates/cbv_app/school_form.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block %}
    <h1>
        {% if not form.instance.pk %}
            Create School
        {% else %}
            Update School
        {% endif %}
    </h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
{% endblock %}

back_end_notes/django/advanced_django_notes/cbv_project/cbv_app/templates/cbv_app/school_list.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block%}
    <h1>Welcome to a list of all the schools!</h1>
    <ol>
        {% for school in schools %}
        <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
        {% endfor %}
    </ol>
{% endblock %}

back_end_notes/django/advanced_django_notes/cbv_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Base</title>
    </head>
    <body>
        <div class="container">
                {% block body_block %}
                {% endblock %}
        </div>
    </body>
</html>

back_end_notes/django/advanced_django_notes/cbv_project/templates/index.html
{% extends "base.html" %}
{% block body_block%}
    <div class="jumbotron">
        <h1>Home Page!</h1>
    </div>
{% endblock %}