back_end_notes/django/level_four_project/level_four_app/urls.py
from django.urls import path
from level_four_app import views

# Template Tagging
app_name = "level_four_app"

urlpatterns = [
    path("relative", views.relative, name="relative"),
    path("other", views.other, name="other")
]

back_end_notes/django/level_four_project/level_four_project/urls.py
from django.contrib import admin
from django.urls import path, include
from level_four_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("level_four_app/", include("level_four_app.urls"))
]

back_end_notes/django/level_four_project/level_four_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {"text": "hello world", "number": 100}
    return render(request, "level_four_app/index.html", context_dict)

def other(request):
    return render(request, "level_four_app/other.html")

def relative(request):
    return render(request, "level_four_app/relative_url_templates.html")

back_end_notes/django/level_four_project/templates/level_four_app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Document</title>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'level_four_app:other' %}">Other</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            <!-- Anything outside of this will be inherited if you extend -->
            {% endblock %}
        </div>
    </body>
</html>

back_end_notes/django/level_four_project/templates/level_four_app/index.html
<!DOCTYPE html>
    {% extends "level_four_app/base.html" %}
        {% block body_block %}
            <h1>Welcome to Index</h1>
            <!-- <h2>This is index.html page showing!</h2> -->
            <h1>{{ text|cut:"world" }}</h1>
            <h1>{{ number|add:"99" }}</h1>
        {% endblock %}

back_end_notes/django/level_four_project/templates/level_four_app/other.html
<!DOCTYPE html>
    {% extends "level_four_app/base.html" %}
        {% block body_block %}
            <h1>Welcome to Other</h1>
            <h2>This is an example of Template Inheritance</h2>
        {% endblock %}
    

back_end_notes/django/level_four_project/templates/level_four_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body>
        <h1>Welcome to Relative Url Templates</h1>
        <a href="{% url 'level_four_app:other' %}">Other</a>
        <a href="{% url 'admin:index'%}">Admin</a>
        <a href="{% url 'index' %}">Index</a>
    </body>
</html>