back_end_notes/django/level_five_project/level_five_app/urls.py
from django.urls import path
from level_five_app import views

app_name = "level_five_app"

urlpatterns = [
    path("register", views.register, name="register"),
    path("user_login", views.user_login, name="user_login")
]

back_end_notes/django/level_five_project/level_five_project/urls.py
from django.contrib import admin
from django.urls import path, include
from level_five_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("level_five_app/", include("level_five_app.urls")),
    path("logout", views.user_logout, name="logout")
]

back_end_notes/django/level_five_project/level_five_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic =  models.ImageField(upload_to="profile_pics", blank=True)

    def __str__(self):
        return self.user.username

back_end_notes/django/level_five_project/level_five_app/forms.py
from django import forms
from django.contrib.auth.models import User
from level_five_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ("username", "email", "password")

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ("portfolio_site", "profile_pic")

back_end_notes/django/level_five_project/level_five_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, "level_five_app/index.html")

def register(request):
    
    registered = False

    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]
            
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, "level_five_app/registration.html", {"user_form": user_form, "profile_form": profile_form, "registered": registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Login Attempt Failed")
            print("Username: {usr} and Password: {pwrd}".format(usr=username, pwrd=password))
            return HttpResponse("Invalid Login")
    else:
        return render(request, "level_five_app/login.html", {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

back_end_notes/django/level_five_project/templates/level_five_app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'level_five_app:register' %}">Register</a></li>
                    
                    {% if user.is_authenticated %}
                        <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="navbar-link" href="{% url 'level_five_app:user_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

back_end_notes/django/level_five_project/templates/level_five_app/basic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
                    <li><a class="navbar-link" href="{% 'admin:index' %}"></a>Admin</li>
                    <li><a class="navbar-link" href="{% url 'level_five_app:register' %}"></a>Register</li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

back_end_notes/django/level_five_project/templates/level_five_app/index.html
{% extends "level_five_app/base.html" %}
{% block body_block %}

    <div class="jumbotron">
        <h1>Django Level Five</h1>
    </div>

{% endblock %}

back_end_notes/django/level_five_project/templates/level_five_app/login.html
{% extends "level_five_app/base.html" %}
{% block body_block %}

<div class="container">
    <h1>Please Login:</h1>
    <form action="{% url 'level_five_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

back_end_notes/django/level_five_project/templates/level_five_app/registration.html
{% extends "level_five_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register Here!</h1>
            <h3>Fill out the form:</h3>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ user_form.as_p}}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register" />
            </form>
        {% endif %}
    </div>
{% endblock%}